"""empty message

Revision ID: efc569397e08
Revises: 653cb9a550c3
Create Date: 2024-10-09 16:39:44.918602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc569397e08'
down_revision = '653cb9a550c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add columns with the proper nullability settings
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('_hashed_password', sa.String(), nullable=True))
        
        # Create a unique constraint with an explicit name
        batch_op.create_unique_constraint("uq_users_username", ['username'])
        
        # Drop the 'password' column, ensuring constraints are handled
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('_hashed_password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
